=== CNemo7539/metawidget/src/java/org/metawidget/inspector/inspection-result-1.0.xsd
<?xml version="1.0" ?>
<xs:schema targetNamespace="http://metawidget.org/inspection-result" xmlns="http://metawidget.org/inspection-result"
	xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
	
	<xs:element name="inspection-result">	
		<xs:complexType>
			<xs:sequence>
				<xs:element name="entity" maxOccurs="unbounded">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="property" minOccurs="0" maxOccurs="unbounded">
								<xs:complexType>
									<xs:attribute name="name" use="required"/>
									<xs:anyAttribute processContents="lax"/>
								</xs:complexType>
							</xs:element>
						</xs:sequence>
						<xs:attribute name="type" use="required"/>
						<xs:anyAttribute processContents="lax"/>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	
</xs:schema>

=== CNemo7539/metawidget/examples/java/org/metawidget/example/swing/addressbook/metawidget-metadata.xml
<?xml version="1.0"?>
<inspection-result xmlns="http://metawidget.org/inspection-result"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://metawidget.org/inspection-result http://metawidget.org/inspection-result/inspection-result-1.0.xsd">

	<!-- Example of using XML. We could have used @UiLookup and @UiLarge annotations instead -->
	
	<entity type="org.metawidget.example.shared.addressbook.model.Contact">
		<property name="title" lookup="Mr, Mrs, Miss, Dr, Cpt" required="true"/>
		<property name="firstname" required="true"/>
		<property name="surname" required="true"/>
		<property name="notes" large="true"/>
	</entity>

	<entity type="org.metawidget.example.shared.addressbook.model.PersonalContact"
			extends="org.metawidget.example.shared.addressbook.model.Contact"/>

	<entity type="org.metawidget.example.shared.addressbook.model.BusinessContact"
			extends="org.metawidget.example.shared.addressbook.model.Contact"/>
	
	<entity type="org.metawidget.example.shared.addressbook.model.Communication">
		<property name="type" lookup="Telephone, Mobile, Fax, E-mail" type="java.lang.String"/>
	</entity>	

</inspection-result>

=== CNemo7539/metawidget/test/java/org/metawidget/test/shared/allwidgets/model/metawidget-metadata.xml
<?xml version="1.0"?>
<inspection-result xmlns="http://metawidget.org/inspection-result"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://metawidget.org/inspection-result http://metawidget.org/inspection-result/inspection-result-1.0.xsd">

	<!-- We use XML, not annotations, because we  -->
	<!-- want to test 'allwidgets' under J2SE 1.4 -->
	
	<entity type="org.metawidget.test.shared.allwidgets.model.AllWidgets">
		<property name="textbox" lookup="" masked="" large="" maximum-length="" required="true"/>
		<property name="limitedTextbox" maximum-length="20"/>
		<property name="textarea" large="true"/>
		<property name="password" masked="true"/>
		<property name="byte"/>
		<property name="byteObject"/>
		<property name="short"/>
		<property name="shortObject"/>
		<property name="int" minimum-value="" maximum-value=""/>
		<property name="integerObject"/>
		<property name="rangedInt" minimum-value="1" maximum-value="100"/>
		<property name="rangedInteger" minimum-value="2" maximum-value="99"/>
		<property name="long"/>
		<property name="longObject" label=" "/>
		<property name="float"/>
		<property name="floatObject" label="nullInBundle"/>
		<property name="double"/>
		<property name="doubleObject" label=""/>
		<property name="char"/>
		<property name="boolean"/>
		<property name="booleanObject"/>
		<property name="dropdown" lookup="foo,dropdown,bar" lookup-labels=""/>
		<property name="dropdownWithLabels" lookup="foo,dropdown,bar" lookup-labels="Foo,Dropdown,Bar"/>
		<property name="nestedWidgets" type="org.metawidget.test.shared.allwidgets.model.AllWidgets$NestedWidgets"/>
		<property name="readOnlyNestedWidgets" type="org.metawidget.test.shared.allwidgets.model.AllWidgets$NestedWidgets" read-only="true"/>
		<property name="readOnlyNestedWidgetsDontExpand" type="org.metawidget.test.shared.allwidgets.model.AllWidgets$NestedWidgets" read-only="true" dont-expand="true"/>
		<property name="date"/>
		<property name="hidden" hidden="true"/>
		<property name="readOnly" read-only="true"/>
		<property name="mystery"/>
		<property name="collection"/>
	</entity>	
	
</inspection-result>
